export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const DISPLAY_ALERT_PASSWORD = 'SHOW_ALERT_PASSWORD'

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = "HANDLE_CHANGE"
export const CLEAR_VALUES = "CLEAR_VALUES"

export const CREATE_PET_BEGIN = "CREATE_JOB_BEGIN"
export const CREATE_PET_SUCCESS = "CREATE_JOB_SUCCESS"
export const CREATE_PET_ERROR = "CREATE_JOB_ERROR"

export const GET_PETS_BEGIN = "GET_PETS_BEGIN"
export const GET_PET_SUCCESS = "GET_PET_SUCCESS"

export const SET_EDIT_PET = "SET_EDIT_PET"

export const DELETE_PET_BEGIN = "DELETE_JOB_BEGIN"

export const EDIT_PET_BEGIN = "EDIT_PET_BEGIN"
export const EDIT_PET_SUCCESS = "EDIT_PET_SUCCESS"
export const EDIT_PET_ERROR = "EDIT_PET_ERROR"

export const CLEAR_FILTERS = "CLEAR_FILTERS"

export const GET_USERS_BEGIN = "GET_USERS_BEGIN"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"

export const SAVE_PET_BEGIN = "SAVE_PET_BEGIN"
export const SAVE_PET_SUCCESS = "SAVE_PET_SUCCESS"
export const SAVE_PET_ERROR = "SAVE_PET_ERROR"

export const DELETESAVE_PET_BEGIN = "DELETESAVE_PET_BEGIN"
export const DELETESAVE_PET_SUCCESS = "DELETESAVE_PET_SUCCESS"

export const GET_SAVED_BEGIN = "GET_SAVED_BEGIN"
export const GET_SAVED_SUCCESS = "GET_SAVED_SUCCESS"
export const GET_SAVED_ERROR = "GET_SAVED_ERROR"

export const OWN_PET_BEGIN = "OWN_PET_BEGIN"
export const OWN_PET_SUCCESS = "OWN_PET_SUCCESS"

export const RETURN_PET_BEGIN = "RETURN_PET_BEGIN"
export const RETURN_PET_SUCCESS = "RETURN_PET_SUCCESS"